name: PHP Syntax Checker

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    php-cs-fixer:
        name: PHP Syntax Checker
        runs-on: ubuntu-latest
        steps:
            - name: Checkout v2
              uses: actions/checkout@v2

            - name: Check PHP syntax errors
              uses: overtrue/phplint@8.0
